import random

# fmt: off
words = [
    'abandon', 'ability', 'able', 'about', 'above', 'absent', 'absorb', 'abstract', 'absurd', 'abuzz',
    'access', 'accident', 'account', 'accuse', 'ace', 'achieve', 'achy', 'acid', 'acned', 'acoustic',
    'acquire', 'across', 'act', 'action', 'actor', 'actress', 'actual', 'acute', 'adapt', 'add', 'addict',
    'address', 'adept', 'adjust', 'admit', 'advance', 'advice', 'aerobic', 'affair', 'afford', 'afire',
    'afoot', 'afoul', 'afraid', 'aft', 'after', 'again', 'age', 'aged', 'agent', 'agile', 'aging', 'aglow',
    'ago', 'agree', 'ahead', 'aided', 'aim', 'air', 'airport', 'airy', 'aisle', 'ajar', 'akin', 'alarm',
    'album', 'alert', 'alien', 'alike', 'alive', 'all', 'alley', 'allow', 'almost', 'alone', 'aloof',
    'alpha', 'already', 'also', 'alter', 'alto', 'always', 'amateur', 'amazing', 'amber', 'among', 'amount',
    'ample', 'amused', 'analyst', 'anchor', 'ancient', 'anger', 'angle', 'angry', 'animal', 'ankle',
    'announce', 'annual', 'another', 'answer', 'antenna', 'anti', 'antic', 'antique', 'antsy', 'anxiety',
    'any', 'apart', 'apish', 'apology', 'appear', 'apple', 'approve', 'april', 'apt', 'arced', 'arch',
    'arctic', 'area', 'arena', 'argue', 'arid', 'arm', 'armed', 'armor', 'army', 'around', 'arrange',
    'arrest', 'arrive', 'arrow', 'art', 'artefact', 'artist', 'artwork', 'ashen', 'ashy', 'ask', 'askew',
    'aspect', 'asset', 'assist', 'assume', 'asthma', 'astir', 'athlete', 'atom', 'atrip', 'attack', 'attend',
    'attic', 'attitude', 'attract', 'auction', 'audit', 'august', 'aunt', 'author', 'auto', 'autumn',
    'average', 'avian', 'avid', 'avocado', 'avoid', 'awake', 'aware', 'awash', 'away', 'awed', 'awesome',
    'awful', 'awing', 'awkward', 'awned', 'awry', 'axial', 'axis', 'azure', 'bachelor', 'back',
    'bacon', 'bad', 'badge', 'bag', 'baggy', 'baked', 'balance', 'balcony', 'bald', 'ball', 'balmy',
    'bamboo', 'banana', 'bandy', 'banner', 'bar', 'bare', 'bared', 'barely', 'bargain', 'barrel', 'basal',
    'base', 'based', 'basic', 'basket', 'bated', 'bats', 'battle', 'batty', 'bay', 'beach', 'beady', 'beamy',
    'bean', 'beat', 'beauty', 'because', 'become', 'beef', 'beefy', 'beery', 'before', 'begin', 'behave',
    'behind', 'beige', 'believe', 'below', 'belt', 'bench', 'benefit', 'bent', 'best', 'beta', 'betray',
    'better', 'between', 'beyond', 'bias', 'bicycle', 'bid', 'bike', 'bind', 'biology', 'birch', 'bird',
    'birth', 'bitter', 'bitty', 'black', 'blade', 'blame', 'bland', 'blank', 'blanket', 'blast', 'bleak',
    'blear', 'bless', 'blind', 'blond', 'blood', 'blossom', 'blouse', 'blown', 'blue', 'bluff', 'blunt',
    'blur', 'blush', 'board', 'boat', 'body', 'boggy', 'bogus', 'boil', 'bold', 'bomb', 'bone', 'boned',
    'bonny', 'bonus', 'bony', 'book', 'boon', 'boost', 'border', 'bored', 'boring', 'born', 'borrow', 'boss',
    'bossy', 'both', 'bottom', 'bounce', 'bound', 'bowed', 'box', 'boxed', 'boxy', 'boy', 'bracket', 'brag',
    'brain', 'brand', 'brash', 'brass', 'brave', 'bread', 'breeze', 'brick', 'bridge', 'brief', 'bright',
    'bring', 'briny', 'brisk', 'broad', 'broccoli', 'broke', 'broken', 'bronze', 'broom', 'brother', 'brown',
    'brush', 'brute', 'bubble', 'buddy', 'budget', 'buff', 'buffalo', 'buggy', 'build', 'built', 'bulb',
    'bulgy', 'bulk', 'bulky', 'bullet', 'bully', 'bum', 'bumpy', 'bundle', 'bunker', 'burden', 'burger',
    'burly', 'burnt', 'burst', 'bus', 'bush', 'bushy', 'business', 'bust', 'busty', 'busy', 'butch',
    'butter', 'buyer', 'buzz', 'cabbage', 'cabin', 'cable', 'cactus', 'cage', 'cake', 'call', 'calm',
    'camera', 'camp', 'campy', 'can', 'canal', 'cancel', 'candy', 'cannon', 'canoe', 'canvas', 'canyon',
    'capable', 'capital', 'captain', 'car', 'carbon', 'card', 'cargo', 'carpet', 'carry', 'cart', 'case',
    'cash', 'casino', 'castle', 'casual', 'cat', 'catalog', 'catch', 'category', 'cattle', 'catty', 'caught',
    'cause', 'caution', 'cave', 'ceiling', 'celery', 'cement', 'census', 'century', 'cereal', 'certain',
    'chair', 'chalk', 'champion', 'change', 'chaos', 'chapter', 'charge', 'chase', 'chat', 'cheap', 'check',
    'cheese', 'chef', 'cherry', 'chest', 'chewy', 'chic', 'chicken', 'chief', 'chimney', 'choice',
    'choose', 'chronic', 'chuckle', 'chunk', 'churn', 'cigar', 'cinnamon', 'circle', 'citizen', 'city',
    'civic', 'civil', 'claim', 'clap', 'clarify', 'claw', 'clay', 'clean', 'clear', 'cleft', 'clerk',
    'clever', 'click', 'client', 'cliff', 'climb', 'clinic', 'clip', 'clock', 'clog', 'close', 'cloth',
    'cloud', 'clown', 'club', 'clump', 'cluster', 'clutch', 'coach', 'coast', 'cocky', 'coconut', 'cod',
    'code', 'coffee', 'coil', 'coin', 'cold', 'collect', 'color', 'column', 'combine', 'come', 'comfort',
    'comfy', 'comic', 'common', 'company', 'concert', 'conduct', 'confirm', 'congress', 'connect',
    'consider', 'control', 'convince', 'cook', 'cool', 'copper', 'copy', 'coral', 'core', 'corn', 'corny',
    'correct', 'cost', 'cosy', 'cotton', 'couch', 'country', 'couple', 'course', 'cousin', 'cover', 'coy',
    'coyote', 'cozy', 'crack', 'cradle', 'craft', 'cram', 'crane', 'crash', 'crater', 'crawl', 'crazy',
    'cream', 'credit', 'creek', 'crew', 'cricket', 'crime', 'crisp', 'critic', 'crop', 'cross', 'crouch',
    'crowd', 'crucial', 'cruel', 'cruise', 'crumble', 'crunch', 'crush', 'cry', 'crystal', 'cube', 'cubic',
    'culture', 'cup', 'cupboard', 'cured', 'curious', 'curly', 'current', 'curt', 'curtain', 'curve',
    'curvy', 'cushion', 'cushy', 'custom', 'cut', 'cute', 'cyan', 'cycle', 'dad', 'daft', 'daily', 'damage',
    'damp', 'dance', 'dandy', 'danger', 'dank', 'daring', 'dark', 'dash', 'dated', 'daughter', 'dawn', 'day',
    'dazed', 'dead', 'deaf', 'deal', 'dear', 'debate', 'debris', 'decade', 'december', 'decide', 'decline',
    'decorate', 'decrease', 'deep', 'deer', 'defense', 'define', 'deft', 'defy', 'degree', 'deist', 'delay',
    'deliver', 'demand', 'demise', 'denial', 'dense', 'dentist', 'deny', 'depart', 'depend', 'deposit',
    'depth', 'deputy', 'derive', 'describe', 'desert', 'design', 'desk', 'despair', 'destroy', 'detail',
    'detect', 'develop', 'device', 'devote', 'dewy', 'diagram', 'dial', 'diamond', 'diary', 'dice', 'dicey',
    'diesel', 'diet', 'differ', 'digital', 'dignity', 'dilemma', 'dim', 'dingy', 'dinky', 'dinner',
    'dinosaur', 'dire', 'direct', 'dirt', 'dirty', 'disagree', 'discover', 'disease', 'dish', 'dismiss',
    'disorder', 'display', 'distance', 'divert', 'divide', 'divorce', 'dizzy', 'doctor', 'document', 'dodgy',
    'dog', 'doll', 'dolphin', 'domain', 'domed', 'donate', 'done', 'donkey', 'donor', 'door', 'doped',
    'dopey', 'dopy', 'dormy', 'dose', 'dosed', 'double', 'dove', 'down', 'downy', 'dozen', 'drab', 'draft',
    'dragon', 'drama', 'drastic', 'draw', 'drawn', 'dread', 'dream', 'drear', 'dress', 'dried', 'drift',
    'drill', 'drink', 'drip', 'drive', 'droll', 'drop', 'drum', 'dry', 'dual', 'duck', 'dud', 'due', 'dull',
    'dumb', 'dummy', 'dune', 'during', 'dusky', 'dust', 'dusty', 'dutch', 'duty', 'dwarf', 'dyed', 'dying',
    'dynamic', 'each', 'eager', 'eagle', 'early', 'earn', 'earth', 'eased', 'easily', 'east', 'easy', 'echo',
    'ecology', 'economy', 'edge', 'edged', 'edgy', 'edit', 'educate', 'eerie', 'effort', 'egg', 'eight',
    'either', 'elbow', 'elder', 'elect', 'electric', 'elegant', 'element', 'elephant', 'elevator', 'elfin',
    'elite', 'else', 'embark', 'embody', 'embrace', 'emerge', 'emotion', 'employ', 'empower', 'empty',
    'enable', 'enact', 'end', 'ended', 'endless', 'endorse', 'enemy', 'energy', 'enforce', 'engage',
    'engine', 'enhance', 'enjoy', 'enlist', 'enough', 'enrich', 'enroll', 'ensure', 'enter', 'entire',
    'entry', 'envelope', 'epic', 'episode', 'equal', 'equip', 'era', 'erase', 'erode', 'erosion', 'error',
    'erupt', 'escape', 'essay', 'essence', 'estate', 'eternal', 'ethics', 'even', 'every', 'evidence',
    'evil', 'evoke', 'evolve', 'exact', 'example', 'excess', 'exchange', 'excite', 'exclude', 'excuse',
    'execute', 'exercise', 'exhaust', 'exhibit', 'exile', 'exist', 'exit', 'exotic', 'expand', 'expect',
    'expire', 'explain', 'expose', 'express', 'extend', 'extra', 'eye', 'eyebrow', 'eyed', 'fab', 'fabric',
    'face', 'faced', 'faculty', 'fade', 'faded', 'faint', 'fair', 'faith', 'fake', 'fall', 'false', 'fame',
    'famed', 'family', 'famous', 'fan', 'fancy', 'fantasy', 'far', 'farm', 'fashion', 'fast', 'fat', 'fatal',
    'fated', 'father', 'fatigue', 'fault', 'favorite', 'fazed', 'feature', 'february', 'federal', 'fee',
    'feed', 'feel', 'female', 'fence', 'feral', 'festival', 'fetch', 'fever', 'few', 'fewer', 'fiber',
    'fiction', 'field', 'fiery', 'fifth', 'fifty', 'figure', 'file', 'film', 'filmy', 'filter', 'final',
    'find', 'fine', 'finer', 'finger', 'finish', 'fire', 'fired', 'firm', 'first', 'fiscal', 'fish', 'fishy',
    'fit', 'fitness', 'five', 'fix', 'fixed', 'fizzy', 'flag', 'flaky', 'flame', 'flash', 'flat', 'flavor',
    'flee', 'fleet', 'flight', 'flint', 'flip', 'float', 'flock', 'floor', 'flower', 'fluid', 'flush', 'fly',
    'foam', 'foamy', 'focal', 'focus', 'fog', 'foggy', 'foil', 'fold', 'follow', 'fond', 'food', 'foot',
    'force', 'fore', 'forest', 'forget', 'fork', 'fortune', 'forum', 'forward', 'fossil', 'foster', 'foul',
    'found', 'four', 'fox', 'foxy', 'fragile', 'frail', 'frame', 'frank', 'free', 'frequent', 'fresh',
    'fried', 'friend', 'fringe', 'frog', 'front', 'frost', 'frown', 'frozen', 'fruit', 'fuel', 'full',
    'fumed', 'fun', 'funky', 'funny', 'furnace', 'furry', 'fury', 'fused', 'fussy', 'future', 'fuzzy',
    'gadget', 'gain', 'galaxy', 'gallery', 'game', 'gap', 'garage', 'garbage', 'garden', 'garlic', 'garment',
    'gas', 'gasp', 'gate', 'gather', 'gaudy', 'gauge', 'gaunt', 'gawky', 'gaze', 'general', 'genius',
    'genre', 'gentle', 'genuine', 'gesture', 'ghost', 'giant', 'giddy', 'gift', 'giggle', 'gimpy', 'ginger',
    'giraffe', 'girl', 'give', 'glad', 'glance', 'glare', 'glass', 'glide', 'glimpse', 'globe', 'gloom',
    'glory', 'glove', 'glow', 'glue', 'glum', 'goat', 'goddess', 'godly', 'going', 'gold', 'gone', 'good',
    'gooey', 'goofy', 'goose', 'gorilla', 'gory', 'gospel', 'gossip', 'govern', 'gown', 'grab', 'grace',
    'grain', 'grand', 'grant', 'grape', 'grass', 'gravity', 'great', 'green', 'grey', 'grid', 'grief',
    'grim', 'grimy', 'grit', 'grocery', 'gross', 'group', 'grow', 'grown', 'gruff', 'grunt', 'guard',
    'guess', 'guide', 'guilt', 'guitar', 'gummy', 'gushy', 'gusty', 'gutsy', 'gym', 'habit', 'hair', 'hairy',
    'hale', 'half', 'halt', 'hammer', 'hammy', 'hamster', 'hand', 'handy', 'happy', 'harbor', 'hard',
    'hardy', 'harsh', 'harvest', 'hasty', 'hat', 'hated', 'have', 'hawk', 'hazard', 'hazel', 'hazy', 'head',
    'health', 'heard', 'heart', 'heavy', 'hedgehog', 'hefty', 'height', 'held', 'hello', 'helmet', 'help',
    'hen', 'here', 'hero', 'hex', 'hexed', 'hidden', 'high', 'hill', 'hilly', 'hind', 'hint', 'hip', 'hire',
    'hired', 'history', 'hoar', 'hoary', 'hobby', 'hockey', 'hokey', 'hold', 'hole', 'holey', 'holiday',
    'hollow', 'holy', 'home', 'homey', 'honey', 'hood', 'hope', 'horn', 'horror', 'horse', 'hospital',
    'host', 'hot', 'hotel', 'hour', 'hover', 'hub', 'huffy', 'huge', 'human', 'humble', 'humid', 'humor',
    'hundred', 'hungry', 'hunt', 'hurdle', 'hurry', 'hurt', 'husband', 'husky', 'hybrid', 'ice', 'icky',
    'icon', 'icy', 'idea', 'ideal', 'identify', 'idle', 'iffy', 'ignore', 'ill', 'illegal', 'illness',
    'image', 'imitate', 'immense', 'immune', 'impact', 'impose', 'improve', 'impulse', 'inane', 'inch',
    'include', 'income', 'increase', 'index', 'indicate', 'indoor', 'industry', 'inept', 'inert',
    'inflict', 'inform', 'inhale', 'inherit', 'initial', 'inject', 'injury', 'inky', 'inmate', 'inner',
    'innocent', 'input', 'inquiry', 'insane', 'insect', 'inside', 'inspire', 'install', 'intact', 'interest',
    'into', 'invest', 'invite', 'involve', 'ionic', 'irate', 'iron', 'island', 'isolate', 'issue', 'item',
    'ivory', 'jacket', 'jade', 'jaded', 'jaggy', 'jaguar', 'jar', 'jawed', 'jazz', 'jazzy', 'jealous',
    'jeans', 'jelly', 'jet', 'jewel', 'job', 'join', 'joint', 'joke', 'jolly', 'journey', 'jowly', 'joy',
    'judge', 'juice', 'juicy', 'jumbo', 'jump', 'jumpy', 'jungle', 'junior', 'junk', 'just', 'kangaroo',
    'keen', 'keep', 'kempt', 'ketchup', 'key', 'keyed', 'khaki', 'kick', 'kidney', 'kin', 'kind',
    'kingdom', 'kinky', 'kiss', 'kit', 'kitchen', 'kite', 'kitten', 'kiwi', 'knee', 'knife', 'knock', 'know',
    'known', 'kooky', 'lab', 'label', 'labor', 'laced', 'lacy', 'ladder', 'lady', 'laid', 'lake', 'lame',
    'lamp', 'language', 'lank', 'lanky', 'laptop', 'large', 'last', 'late', 'later', 'latin', 'laugh',
    'laundry', 'lava', 'law', 'lawn', 'lawsuit', 'lax', 'lay', 'layer', 'lazy', 'leader', 'leaf', 'leafy',
    'leaky', 'lean', 'learn', 'least', 'leave', 'lecture', 'left', 'leg', 'legal', 'legend', 'leisure',
    'lemon', 'lend', 'length', 'lens', 'leopard', 'less', 'lesson', 'letter', 'level', 'liar', 'liberty',
    'library', 'license', 'life', 'lift', 'light', 'like', 'liked', 'limb', 'limit', 'limp', 'lined', 'link',
    'lion', 'liquid', 'list', 'lit', 'little', 'live', 'liver', 'livid', 'lizard', 'load', 'loamy', 'loan',
    'lobster', 'local', 'lock', 'loco', 'lofty', 'logic', 'lone', 'lonely', 'long', 'loony', 'loop', 'loopy',
    'loose', 'lossy', 'lost', 'lottery', 'loud', 'lounge', 'lousy', 'love', 'loved', 'low', 'lowly', 'loyal',
    'lucid', 'lucky', 'luggage', 'lumber', 'lumpy', 'lunar', 'lunch', 'lurid', 'lush', 'lusty', 'luxury',
    'lyric', 'lyrics', 'machine', 'macho', 'macro', 'mad', 'made', 'magic', 'magnet', 'maid', 'mail', 'main',
    'major', 'make', 'male', 'mammal', 'man', 'manage', 'mandate', 'mango', 'mangy', 'manic', 'manly',
    'mansion', 'manual', 'many', 'maple', 'marble', 'march', 'margin', 'marine', 'market', 'marriage',
    'mask', 'mass', 'master', 'match', 'material', 'math', 'matrix', 'matt', 'matte', 'matter', 'mauve',
    'maximum', 'maze', 'meadow', 'mealy', 'mean', 'measure', 'meat', 'meaty', 'mechanic', 'medal', 'media',
    'meek', 'meet', 'melody', 'melt', 'member', 'memory', 'mention', 'menu', 'mercy', 'mere', 'merge',
    'merit', 'merry', 'mesh', 'message', 'messy', 'metal', 'method', 'micro', 'middle', 'midnight', 'mild',
    'milk', 'milky', 'million', 'mimic', 'mind', 'mined', 'mini', 'minimum', 'minor', 'mint', 'minty',
    'minus', 'minute', 'miracle', 'mired', 'mirky', 'mirror', 'misery', 'miss', 'mistake', 'misty', 'mix',
    'mixed', 'mixture', 'mobile', 'mock', 'mod', 'modal', 'model', 'modify', 'moist', 'molar', 'moldy',
    'mom', 'moment', 'monitor', 'monkey', 'mono', 'monster', 'month', 'moody', 'moon', 'moony', 'moot',
    'moral', 'more', 'morning', 'mosquito', 'mossy', 'most', 'mother', 'mothy', 'motion', 'motor',
    'mountain', 'mouse', 'mousy', 'move', 'moved', 'movie', 'mown', 'much', 'mucky', 'muddy', 'muffin',
    'muggy', 'mule', 'multiply', 'mum', 'mural', 'murky', 'muscle', 'museum', 'mushroom', 'mushy', 'music',
    'musky', 'must', 'musty', 'mute', 'muted', 'mutual', 'myself', 'mystery', 'myth', 'naive', 'name',
    'napkin', 'narrow', 'nary', 'nasal', 'nasty', 'natal', 'nation', 'natty', 'nature', 'naval', 'near',
    'neat', 'neck', 'need', 'needy', 'negative', 'neglect', 'neither', 'nephew', 'nerve', 'nervy', 'nest',
    'net', 'network', 'neutral', 'never', 'new', 'news', 'newsy', 'next', 'nice', 'nifty', 'nigh', 'night',
    'nine', 'ninth', 'noble', 'noise', 'noisy', 'nominee', 'none', 'noodle', 'normal', 'north', 'nose',
    'nosed', 'notable', 'note', 'noted', 'nothing', 'notice', 'novel', 'now', 'nubby', 'nuclear', 'numb',
    'number', 'nurse', 'nut', 'nuts', 'nutty', 'oak', 'oaken', 'oaten', 'obese', 'obey', 'object', 'oblige',
    'obscure', 'observe', 'obtain', 'obvious', 'occur', 'ocean', 'october', 'odd', 'odor', 'off', 'offer',
    'office', 'often', 'oil', 'oiled', 'oily', 'okay', 'old', 'olden', 'older', 'olive', 'olympic', 'omit',
    'once', 'one', 'onion', 'online', 'only', 'oozy', 'open', 'opera', 'opinion', 'oppose', 'optic',
    'option', 'oral', 'orange', 'orbit', 'orchard', 'order', 'ordinary', 'organ', 'orient', 'original',
    'orphan', 'ostrich', 'other', 'out', 'outdoor', 'outer', 'output', 'outside', 'oval', 'oven', 'over',
    'overt', 'owing', 'own', 'owned', 'owner', 'oxygen', 'oyster', 'ozone', 'pact', 'paddle', 'pagan',
    'page', 'paid', 'pair', 'palace', 'pale', 'palm', 'palmy', 'panda', 'panel', 'panic', 'panther', 'paper',
    'parade', 'parent', 'park', 'parrot', 'party', 'pass', 'past', 'pasty', 'pat', 'patch', 'path',
    'patient', 'patrol', 'pattern', 'pause', 'pave', 'paved', 'payment', 'peace', 'peaky', 'peanut', 'pear',
    'peasant', 'peaty', 'pedal', 'pelican', 'pen', 'penalty', 'pencil', 'pent', 'people', 'pepper', 'peppy',
    'perfect', 'perky', 'permit', 'person', 'pert', 'pesky', 'pet', 'petty', 'phone', 'phony', 'photo',
    'phrase', 'physical', 'piano', 'picky', 'picnic', 'picture', 'piece', 'pied', 'pig', 'pigeon', 'piggy',
    'pilar', 'pill', 'pilot', 'pink', 'pioneer', 'pipe', 'pitch', 'pizza', 'place', 'plain', 'plane',
    'planet', 'plastic', 'plate', 'play', 'please', 'pledge', 'pluck', 'plug', 'plumb', 'plump', 'plunge',
    'plus', 'plush', 'poem', 'poet', 'point', 'polar', 'pole', 'police', 'pond', 'pony', 'pool', 'poor',
    'pop', 'popular', 'port', 'portion', 'posed', 'posh', 'position', 'possible', 'post', 'potato',
    'pottery', 'potty', 'poverty', 'powder', 'power', 'practice', 'praise', 'predict', 'prefer', 'prepare',
    'present', 'pretty', 'prevent', 'price', 'pricy', 'pride', 'prim', 'primary', 'print', 'prior',
    'priority', 'prison', 'private', 'privy', 'prize', 'problem', 'process', 'produce', 'profit', 'program',
    'project', 'promote', 'prone', 'proof', 'property', 'prosper', 'prosy', 'protect', 'proud', 'provide',
    'public', 'pudding', 'pudgy', 'puff', 'puffy', 'pull', 'pulp', 'pulpy', 'pulse', 'pumpkin', 'punch',
    'punk', 'puny', 'pupal', 'pupil', 'puppy', 'purchase', 'pure', 'purity', 'purpose', 'purse', 'push',
    'pushy', 'put', 'puzzle', 'pyramid', 'quack', 'quality', 'quantum', 'quarter', 'quasi', 'question',
    'quick', 'quiet', 'quit', 'quiz', 'quote', 'rabbit', 'rabid', 'raccoon', 'race', 'rack', 'radar',
    'radio', 'rail', 'rain', 'rainy', 'raise', 'rally', 'ramp', 'ranch', 'random', 'range', 'rapid', 'rare',
    'rash', 'raspy', 'rate', 'rather', 'ratty', 'raven', 'raw', 'razor', 'ready', 'real', 'rear', 'reason',
    'rebel', 'rebuild', 'recall', 'receive', 'recipe', 'record', 'recycle', 'red', 'reduce', 'reflect',
    'reform', 'refuse', 'regal', 'region', 'regret', 'regular', 'reject', 'relax', 'release', 'relief',
    'rely', 'remain', 'remember', 'remind', 'remove', 'render', 'renew', 'rent', 'reopen', 'repair',
    'repeat', 'replace', 'report', 'require', 'rescue', 'resemble', 'resist', 'resource', 'response',
    'result', 'retire', 'retreat', 'retro', 'return', 'reunion', 'reveal', 'review', 'reward', 'rhythm',
    'rib', 'ribbon', 'rice', 'rich', 'ride', 'ridge', 'rife', 'right', 'rigid', 'riled', 'ring', 'riot',
    'ripe', 'ripple', 'risen', 'risk', 'risky', 'ritual', 'ritzy', 'rival', 'river', 'road', 'roast',
    'robed', 'robot', 'robust', 'rocket', 'rocky', 'romance', 'roof', 'rookie', 'room', 'roomy', 'ropey',
    'rose', 'rosy', 'rotate', 'rough', 'round', 'route', 'rowdy', 'royal', 'rubber', 'ruby', 'rude', 'rug',
    'rule', 'ruled', 'rummy', 'run', 'runic', 'runny', 'runty', 'runway', 'rural', 'rush', 'rushy', 'rust',
    'rusty', 'rutty', 'sad', 'saddle', 'sadness', 'safe', 'sage', 'said', 'sail', 'salad', 'salmon', 'salon',
    'salt', 'salty', 'salute', 'same', 'sample', 'sand', 'sandy', 'sane', 'sappy', 'sassy', 'satisfy',
    'satoshi', 'sauce', 'sausage', 'saute', 'save', 'saved', 'say', 'scale', 'scaly', 'scan', 'scant',
    'scare', 'scary', 'scatter', 'scene', 'scheme', 'school', 'science', 'scissors', 'scorpion', 'scout',
    'scrap', 'screen', 'script', 'scrub', 'sea', 'seamy', 'sear', 'search', 'season', 'seat', 'second',
    'secret', 'section', 'security', 'seed', 'seedy', 'seek', 'segment', 'select', 'self', 'sell', 'seminar',
    'senior', 'sense', 'sent', 'sentence', 'series', 'service', 'session', 'settle', 'setup', 'seven',
    'sewed', 'sewn', 'shadow', 'shady', 'shaft', 'shaky', 'shallow', 'sham', 'share', 'sharp', 'shed',
    'sheer', 'shell', 'sheriff', 'shield', 'shift', 'shine', 'shiny', 'ship', 'shiver', 'shock', 'shoe',
    'shoot', 'shop', 'short', 'shot', 'shoulder', 'shove', 'showy', 'shrimp', 'shrug', 'shuffle', 'shut',
    'shy', 'sibling', 'sick', 'side', 'siege', 'sight', 'sign', 'silent', 'silk', 'silky', 'silly', 'silty',
    'silver', 'similar', 'simple', 'since', 'sing', 'siren', 'sissy', 'sister', 'situate', 'six', 'sixth',
    'sixty', 'size', 'sized', 'skate', 'sketch', 'skew', 'ski', 'skill', 'skim', 'skin', 'skirt', 'skull',
    'slab', 'slack', 'slain', 'slam', 'slaty', 'slav', 'sleek', 'sleep', 'slender', 'slice', 'slick',
    'slide', 'slight', 'slim', 'slimy', 'slogan', 'slot', 'slow', 'slush', 'sly', 'small', 'smart', 'smile',
    'smoke', 'smoky', 'smooth', 'smug', 'snack', 'snake', 'snaky', 'snap', 'sneak', 'snide', 'sniff', 'snow',
    'snowy', 'snub', 'snuff', 'snug', 'soap', 'soapy', 'sober', 'soccer', 'social', 'sock', 'soda', 'soft',
    'soggy', 'solar', 'sold', 'soldier', 'sole', 'solid', 'solo', 'solution', 'solve', 'some', 'someone',
    'song', 'soon', 'sooty', 'sore', 'sorry', 'sort', 'soul', 'sound', 'soup', 'soupy', 'sour', 'source',
    'south', 'sown', 'space', 'spare', 'spatial', 'spawn', 'speak', 'special', 'speed', 'spell', 'spend',
    'spent', 'sphere', 'spice', 'spicy', 'spider', 'spike', 'spiky', 'spin', 'spiny', 'spirit', 'splay',
    'split', 'spoil', 'sponsor', 'spoon', 'sport', 'spot', 'spray', 'spread', 'spring', 'spry', 'spumy',
    'spy', 'squab', 'square', 'squat', 'squeeze', 'squirrel', 'stable', 'stadium', 'staff', 'stage', 'stagy',
    'stairs', 'stale', 'stamp', 'stand', 'star', 'stark', 'start', 'state', 'stay', 'steak', 'steel',
    'steep', 'stem', 'step', 'stereo', 'stern', 'stick', 'stiff', 'still', 'sting', 'stock', 'stomach',
    'stone', 'stony', 'stool', 'story', 'stout', 'stove', 'strategy', 'straw', 'stray', 'street', 'strike',
    'strong', 'struggle', 'stuck', 'student', 'stuff', 'stumble', 'stung', 'style', 'suave', 'subject',
    'submit', 'subway', 'success', 'such', 'sudden', 'sudsy', 'suffer', 'sugar', 'suggest', 'suit', 'sulky',
    'summer', 'sun', 'sunk', 'sunny', 'sunset', 'super', 'supply', 'supreme', 'sure', 'surface', 'surge',
    'surly', 'surprise', 'surround', 'survey', 'suspect', 'sustain', 'swallow', 'swamp', 'swap', 'swarm',
    'swear', 'sweet', 'swell', 'swept', 'swift', 'swim', 'swing', 'swish', 'switch', 'sword', 'sworn',
    'symbol', 'symptom', 'syrup', 'system', 'tabby', 'table', 'taboo', 'tackle', 'tacky', 'tag', 'tail',
    'taken', 'talent', 'talk', 'talky', 'tall', 'tame', 'tamed', 'tan', 'tangy', 'tank', 'tape', 'taped',
    'tardy', 'target', 'tart', 'task', 'taste', 'tasty', 'tattoo', 'tawny', 'taxi', 'teach', 'teal', 'team',
    'tell', 'ten', 'tenant', 'tennis', 'tenor', 'tense', 'tent', 'tenth', 'tepid', 'term', 'terse', 'test',
    'testy', 'text', 'thank', 'that', 'theme', 'then', 'theory', 'there', 'they', 'thick', 'thin', 'thing',
    'third', 'this', 'thought', 'three', 'thrive', 'throw', 'thumb', 'thunder', 'ticket', 'tidal', 'tide',
    'tidy', 'tied', 'tiger', 'tight', 'tiled', 'tilt', 'timber', 'time', 'timed', 'timid', 'tinny', 'tiny',
    'tip', 'tipsy', 'tired', 'tissue', 'title', 'toast', 'today', 'toddler', 'toe', 'toed', 'together',
    'toilet', 'token', 'tomato', 'tomorrow', 'tonal', 'tone', 'toned', 'tongue', 'tonic', 'tonight', 'tool',
    'tooth', 'top', 'topic', 'topple', 'tops', 'torch', 'torn', 'tornado', 'tortoise', 'toss', 'total',
    'tough', 'tourist', 'toward', 'tower', 'town', 'toy', 'track', 'trade', 'traffic', 'tragic', 'train',
    'transfer', 'trap', 'trash', 'travel', 'tray', 'treat', 'tree', 'trend', 'trial', 'tribe', 'trick',
    'tried', 'trig', 'trim', 'trip', 'trite', 'trophy', 'trouble', 'truck', 'true', 'truly', 'trumpet',
    'trust', 'truth', 'try', 'tubby', 'tube', 'tubed', 'tuition', 'tumble', 'tumid', 'tuna', 'tunnel',
    'turkey', 'turn', 'turtle', 'twee', 'twelve', 'twenty', 'twice', 'twin', 'twist', 'two', 'type',
    'typical', 'ugly', 'ultra', 'umbrella', 'unable', 'unaware', 'uncle', 'uncover', 'uncut', 'under',
    'undo', 'undue', 'unfair', 'unfed', 'unfit', 'unfold', 'unhappy', 'uniform', 'union', 'unique', 'unit',
    'universe', 'unknown', 'unlit', 'unlock', 'until', 'unusual', 'unveil', 'unwed', 'update', 'upgrade',
    'uphold', 'upon', 'upper', 'upset', 'urban', 'urge', 'usage', 'use', 'used', 'useful', 'useless',
    'usual', 'utility', 'utter', 'vacant', 'vacuum', 'vague', 'vain', 'valid', 'valley', 'valve', 'van',
    'vanish', 'vapid', 'vapor', 'various', 'vast', 'vault', 'vehicle', 'velvet', 'vendor', 'venture',
    'venue', 'verb', 'verify', 'version', 'very', 'vessel', 'veteran', 'viable', 'vibrant', 'vicious',
    'victory', 'video', 'view', 'village', 'vintage', 'violin', 'viral', 'virtual', 'virus', 'visa', 'visit',
    'visual', 'vital', 'vivid', 'vocal', 'voice', 'void', 'volcano', 'volume', 'vote', 'voyage', 'wacky',
    'wage', 'wagon', 'wait', 'walk', 'wall', 'walnut', 'want', 'warm', 'warrior', 'wary', 'wash', 'washy',
    'wasp', 'waste', 'water', 'wave', 'wavy', 'waxed', 'waxen', 'waxy', 'way', 'weak', 'wealth', 'wear',
    'weary', 'weasel', 'weather', 'web', 'wedding', 'weedy', 'weekend', 'weeny', 'weepy', 'weird', 'welcome',
    'well', 'welsh', 'west', 'wet', 'whale', 'what', 'wheat', 'wheel', 'when', 'where', 'whiny', 'whip',
    'whisper', 'white', 'whole', 'wide', 'width', 'wife', 'wild', 'will', 'wily', 'wimpy', 'win', 'window',
    'windy', 'wine', 'wing', 'wink', 'winner', 'winter', 'wire', 'wired', 'wiry', 'wisdom', 'wise', 'wish',
    'wispy', 'witness', 'witty', 'wolf', 'woman', 'wonder', 'wonky', 'wood', 'woody', 'wool', 'wooly',
    'woozy', 'word', 'wordy', 'work', 'world', 'wormy', 'worn', 'worry', 'worse', 'worst', 'worth', 'wound',
    'woven', 'wrap', 'wreck', 'wrestle', 'wrist', 'write', 'wrong', 'wroth', 'wry', 'yard', 'year', 'yellow',
    'you', 'young', 'youth', 'yucky', 'yummy', 'zany', 'zebra', 'zero', 'zesty', 'zippy', 'zonal', 'zone', 'zoo'
]
# fmt: on


def generate_id():
    # k = 2 --> 2772^2 --> 7.6 million
    # k = 3 --> 2772^3 --> 21.3 billion
    # Realistically, k=2 is plenty, but to reduce collisions
    # where I have to retry creating an ID and making another
    # DB call, I went with k = 3 instead
    return "-".join(random.choices(words, k=3))


if __name__ == "__main__":
    # print(sorted(list(set(words))))
    for _ in range(0, 100):
        print(generate_id())
    print(len(words))
    pass
